name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  dio: ^5.4.3+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^6.0.3
  logger: ^2.3.0
  latlong2: ^0.9.1
  intl: ^0.19.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# Branding Configurations
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/branding/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/branding/logo_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/branding/logo_splash.png"
  android_12:
    image: "assets/branding/logo_splash.png"
    icon_background_color: "#FFFFFF"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/branding/
